-- Make sure MAJOR table is created first since STUDENT references MAJOR_CODE as its foreign key
CREATE TABLE IF NOT EXISTS MAJOR (
	MAJOR_CODE INTEGER UNSIGNED AUTO_INCREMENT,
    MAJOR_NAME VARCHAR(255) NOT NULL,
    REQUIRED_GPA FLOAT(3, 2) NOT NULL,
    PRIMARY KEY (MAJOR_CODE),
    CONSTRAINT MC_CHECK1 CHECK (REQUIRED_GPA BETWEEN 0 AND 4)
);

SELECT * FROM MAJOR;	

INSERT INTO MAJOR (MAJOR_NAME, REQUIRED_GPA) VALUES ('Computer Science', 3.5);
INSERT INTO MAJOR (MAJOR_NAME, REQUIRED_GPA) VALUES ('Biology', 3.2);
INSERT INTO MAJOR (MAJOR_NAME, REQUIRED_GPA) VALUES ('Mathematics', 3.8);
INSERT INTO MAJOR (MAJOR_NAME, REQUIRED_GPA) VALUES ('Psychology', 3.0);
INSERT INTO MAJOR (MAJOR_NAME, REQUIRED_GPA) VALUES ('Engineering', 3.6);


CREATE TABLE IF NOT EXISTS STUDENT (
	STUDENT_ID INTEGER UNSIGNED AUTO_INCREMENT,
    STUDENT_FNAME VARCHAR(255) NOT NULL,
    STUDENT_LNAME VARCHAR(255) NOT NULL,
    STUDENT_GPA FLOAT(3, 2) NOT NULL,
    MAJOR_CODE INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (STUDENT_ID),
    FOREIGN KEY (MAJOR_CODE) REFERENCES MAJOR (MAJOR_CODE) ON UPDATE CASCADE,
    CONSTRAINT S_CHECK1 CHECK (STUDENT_GPA BETWEEN 0 AND 4)
);

SELECT * FROM STUDENT;

INSERT INTO STUDENT (STUDENT_FNAME, STUDENT_LNAME, STUDENT_GPA, MAJOR_CODE) VALUES ('John', 'Doe', 3.7, 1);
INSERT INTO STUDENT (STUDENT_FNAME, STUDENT_LNAME, STUDENT_GPA, MAJOR_CODE) VALUES ('Jane', 'Smith', 3.5, 2);
INSERT INTO STUDENT (STUDENT_FNAME, STUDENT_LNAME, STUDENT_GPA, MAJOR_CODE) VALUES ('Michael', 'Johnson', 3.9, 3);
INSERT INTO STUDENT (STUDENT_FNAME, STUDENT_LNAME, STUDENT_GPA, MAJOR_CODE) VALUES ('Emily', 'Williams', 3.2, 4);
INSERT INTO STUDENT (STUDENT_FNAME, STUDENT_LNAME, STUDENT_GPA, MAJOR_CODE) VALUES ('David', 'Brown', 3.6, 5);
INSERT INTO STUDENT (STUDENT_FNAME, STUDENT_LNAME, STUDENT_GPA, MAJOR_CODE) VALUES ('Sarah', 'Miller', 3.4, 1);
INSERT INTO STUDENT (STUDENT_FNAME, STUDENT_LNAME, STUDENT_GPA, MAJOR_CODE) VALUES ('Christopher', 'Davis', 3.8, 2);
INSERT INTO STUDENT (STUDENT_FNAME, STUDENT_LNAME, STUDENT_GPA, MAJOR_CODE) VALUES ('Jessica', 'Wilson', 3.1, 3);
INSERT INTO STUDENT (STUDENT_FNAME, STUDENT_LNAME, STUDENT_GPA, MAJOR_CODE) VALUES ('Andrew', 'Taylor', 3.3, 4);
INSERT INTO STUDENT (STUDENT_FNAME, STUDENT_LNAME, STUDENT_GPA, MAJOR_CODE) VALUES ('Michelle', 'Anderson', 3.6, 5);


